<h2>PRO plan offers:</h2>
<p style="font-size:16px; max-width:72%;">Take control of your registration process with the Pro version of CM Email Registration Blacklist. Use the Domain Blacklist feature to block unwanted email domains and ensure only legitimate users can register.</p>
<br>
<div style="float:left; width:100%; margin-bottom:30px;">
<div style="text-align:center; width:300px; float:left; margin-right:20px;">
<a href="<?php echo plugins_url('../../assets/images/01-cm-email-registration-blacklist-domain-blacklist.png', __FILE__); ?>" target="_blank" style="text-decoration:none;">
	<img src="<?php echo plugins_url('../../assets/images/01-cm-email-registration-blacklist-domain-blacklist.png', __FILE__); ?>" alt="" style="width:100%; border:1px solid #444;" />
</a>
<span style="font-size:15px;">Domain Blacklist</span>
</div>
</div>
<br>
<h3>Upgrade to Pro for:</h3>
<ul style="font-size:16px;list-style:none;margin:0;">
<li><svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Adding specific domains to a blacklist for restricted access.</li>
<li><svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Blocking disposable and suspicious email domains.</li>
<li><svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Enhancing site security by preventing spam registrations.</li>
</ul>
<br>
<a href="<?php echo admin_url('admin.php?page=cmeb_pro'); ?>" style="font-size: 16px; line-height: 20px; font-weight: 500; padding: 10px 30px; background-color: #008000; border-color: #008000; color: #fff; text-decoration:none;">Upgrade to Pro</a>
<br>
<br>